// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///


public static class GPGSIds
{
    // 이걸 내가 정리한다고 야발
    public const string achievement_1 = "CgkIyN3ap84EEAIQAw"; // 학생증 발급
    public const string achievement_2 = "CgkIyN3ap84EEAIQBA"; // 시작이 반일꺼야
    public const string achievement_3 = "CgkIyN3ap84EEAIQBQ"; // 시작이 반이 아니였네
    public const string achievement_4 = "CgkIyN3ap84EEAIQBg"; // 이제는 정말 반이네
    public const string achievement_5 = "CgkIyN3ap84EEAIQBw"; // 방황하는 펜촉
    public const string achievement_6 = "CgkIyN3ap84EEAIQCA"; // 대학생활도 끝이 보이네
    public const string achievement_7 = "CgkIyN3ap84EEAIQCQ"; // 학생증 > 사원증
    public const string achievement_8 = "CgkIyN3ap84EEAIQCg"; // 교수님의 사랑
    public const string achievement_9 = "CgkIyN3ap84EEAIQCw"; // 교수님의 귀염둥이
    public const string achievement_10 = "CgkIyN3ap84EEAIQFQ"; // 일반대학생
    public const string achievement_11 = "CgkIyN3ap84EEAIQDA"; // 일탈을 꿈꾸는 소시민
    public const string achievement_12 = "CgkIyN3ap84EEAIQDg"; // 시대를 앞서가는 혁명의 씨앗
    public const string achievement_13 = "CgkIyN3ap84EEAIQDw"; // 야? 좋냐?
    public const string achievement_14 = "CgkIyN3ap84EEAIQEA"; // 야? 우냐?
    public const string achievement_15 = "CgkIyN3ap84EEAIQEQ"; // 펜을 막 잡은
    public const string achievement_16 = "CgkIyN3ap84EEAIQEg"; // 필기마스터
    public const string achievement_17 = "CgkIyN3ap84EEAIQEw"; // 인생 n 회차
    public const string achievement_18 = "CgkIyN3ap84EEAIQFA"; // 16비트 운영체제

}

